# Generated by Django 6.0.3 on 2026-04-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_seed_tutorials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['order', 'created_at']},
        ),
    ]
