# Generated by Django 6.0.3 on 2026-04-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_add_website_resources'),
        ('tutorials', '0004_alter_tutorial_options'),
    ]

    operations = [
    ]
