# Generated by Django 6.0.3 on 2026-03-24 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'File Hash'), ('email', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=255, unique=True)),
                ('reputation_score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.5)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_iocs', to='analysis.analysisresult')),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_links', to='ioc.ioc')),
            ],
        ),
    ]
